# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_auto_20180715_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Euro amount'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
