# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0003_auto_20180716_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.AddField(
            model_name='food',
            name='availability',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Shs amount'),
        ),
    ]
