# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_auto_20180717_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='post_code',
        ),
    ]
