# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0006_auto_20180718_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('food_name', models.CharField(max_length=30)),
                ('table_number', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('mode', models.NullBooleanField(choices=[(True, 'Plate'), (False, 'Takeaway')])),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='town',
        ),
        migrations.AlterField(
            model_name='food',
            name='availability',
            field=models.NullBooleanField(choices=[(True, 'Available'), (False, 'Unavailable')]),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
