# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0007_auto_20180719_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='picture',
            new_name='image',
        ),
    ]
