# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0008_auto_20180719_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='picture',
        ),
    ]
