# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0010_auto_20180720_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Unavailable', max_length=50),
        ),
    ]
